# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('inspection_type', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_score', models.CharField(max_length=100)),
                ('source_agency', models.CharField(choices=[('carrollton', 'City of Carrollton'), ('dallas', 'City of Dallas'), ('fort_worth', 'City of Fort Worth'), ('plano', 'City of Plano'), ('richardson', 'City of Richardson'), ('tarrant_county', 'Tarrant County')], max_length=25)),
                ('normalized_numeric_grade', models.IntegerField()),
                ('normalized_letter_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.Establishment')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_deducted', models.IntegerField(blank=True, null=True)),
                ('statute_citation', models.TextField(blank=True, null=True)),
                ('infraction_category', models.TextField()),
                ('inspector_comment', models.TextField()),
                ('severity', models.CharField(blank=True, max_length=25, null=True)),
                ('corrected_during_inspection', models.NullBooleanField()),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('violation_count', models.IntegerField(blank=True, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.Inspection')),
            ],
        ),
    ]
