# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'get_latest_by': 'date'},
        ),
    ]
