# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_auto_20170810_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'get_latest_by': 'date', 'ordering': ['-date']},
        ),
    ]
