# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_auto_20170811_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='violation',
            options={'ordering': ['-points_deducted', 'infraction_category']},
        ),
    ]
